//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioMetrixCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public long ID { get; set; }
        public int MachineNumber { get; set; }
        public int IndRegID { get; set; }
        public string DateTimeRecord { get; set; }
        public DateTime DateTimeOriginal { get; set; }
        public DateTime DateOnlyRecord { get; set; }
        public DateTime TimeOnlyRecord { get; set; }
    }
}
